# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-checkout"
client_id = "6a60acd8615ec57bc967dd7d3b2c43d3"
application_url = "https://now-northeast-estate-preferred.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://now-northeast-estate-preferred.trycloudflare.com/auth/callback",
  "https://now-northeast-estate-preferred.trycloudflare.com/auth/shopify/callback",
  "https://now-northeast-estate-preferred.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-desire.myshopify.com"
